### ISSUE TITLE
500 error using API

### ISSUE THREAD

**Issue by leonawicz** [cezarykluczynski/stapi#10]
I am receiving 500 status code when using the API through a client or through the [API browser](http://stapi.co/api-browser). It is presumably the same error via the API browser, though it does not specify any details or codes. I tried various searches. I receive the error via local and various remote client builds. So it does not appear related to my person computer or internet connection.

I would like to retain STAPI as one of the API services offered by my Star Trek data analysis client (R package), but the online repository it is published to is requiring that I address the issue in my client soon. Please let me know if STAPI is still supported. Kind regards,
Matt

**Comment by cezarykluczynski** [comment]
Yes, it's still supported. There was an issue connecting to the database, but it's resolved now. Sorry about that.

**Comment by leonawicz** [comment]
Great! :) I can confirm it is working again. Thank you!
