### ISSUE TITLE
Calls returning 500

### ISSUE THREAD

**Issue by cgwilsonnoctroe** [cezarykluczynski/stapi#12]
Hi, when making some calls I am receiving a 500 error, I figure it is probably related to the previous issue but in case it's not I wanted to mention it. 

Specifically any endpoint for books with page numbers > 1

http://stapi.co/api/v1/rest/book/search?pageNumber=2

[](https://github.com/cezarykluczynski/stapi/issues/10)

**Comment by cezarykluczynski** [comment]
Sorry for that. It should be fixed now.

**Comment by cgwilsonnoctroe** [comment]
Confirmed, thank you so much for your work!
