### ISSUE TITLE
As a developer, I want to use python as a client. 

### ISSUE THREAD

**Issue by MaximeGir** [cezarykluczynski/stapi#2]
Acceptance :
1. unit tests for endpoints 
2. either writing a python client or a python wrapper, 

What do you think?  

_Sent from my Huawei Nexus 6P using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by cezarykluczynski** [comment]
Hi Maxime,

It would be great if you gonna be willing to mantain a Python client for STAPI. But ff you just want to grab data for your project, that's OK too.

The best approach here would be to download ZIP containing either Swagger specs or SOAP contracts from [API documentaion page](http://stapi.co/api-documentation). Then you can try to generate scaffold Python client from it. [swagger-codegen](https://github.com/swagger-api/swagger-codegen) is a way to go for Swagger. For SOAP, probably [ZSI](http://pywebsvcs.sourceforge.net/) can be used, but I'm by far not an expert on Python.

I think that, before attempting to write client from scratch, you should at least try to generate client code, then write a minimal wrapper around it.

As for the unit tests, I won't have resources to actively participate in the Python client development, so won't be telling anyone how to write their code. For generated code, however, I wouldn't write unit tests, but rather a integration tests, to check if you can connect to every endpoint.

If you have any problem generating the code, please don't hesitate to report it (Java clients generates fine).

**Comment by MaximeGir** [comment]
Ok, I'll try to set it up locally ti grab the data first, it's a spring boot app? I know next to nothing about java spring. Do I have to generate some code via gradle before running the server? 

_Sent from my Huawei Nexus 6P using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by cezarykluczynski** [comment]
Yes, it's based on Spring Boot.

If you want to run it locally, follow the steps from [here](https://github.com/cezarykluczynski/stapi/wiki/Development). All that's necessary to run STAPI locally is described there. Code generation is described there too. I suggest importing project into IntelliJ IDEA - that's what I'm using. Other IDE's were not tested.

Do git pull too. I've just updated missing configuration properties. Documentation on wiki was also put up to date.

**Comment by cezarykluczynski** [comment]
One other thing: please stick to the tagged released (I've just released v0.0.1). Commits between tagged releases will not guarantee backward compatibility of database schema migrations.
