### ISSUE TITLE
http security issues

### ISSUE THREAD

**Issue by missalyss** [cezarykluczynski/stapi#9]
Curious if you have any plans to update to `https`? It's proving to make it difficult to make calls to the API in production because my url is `https` and won't make calls to `http`. Still looking at work arounds. 

Also, thanks for bringing all this information together! Fantastic collection of data.

**Comment by cezarykluczynski** [comment]
Eventually HTTPS will be supported, but not until stapi.co is moved to Docker and AWS, and I can't really give any timeline for that.

A workaround I can offer is that you create a HTTPS proxy on your side, and redirect all calls from your website to stapi.co through that proxy.

**Comment by cezarykluczynski** [comment]
It's been a while, but STAPI now has SSL: https://stapi.co/

**Comment by cezarykluczynski** [comment]
Closing as this is now resolved.
